# Enable Flutter recommended lints
include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    # Ví dụ:
    # avoid_print: false
    # prefer_single_quotes: true

custom_lint:
  rules:
    # Có thể bật / tắt từng rule của flutter_hooks_lint
    # hooks_unuse_widget: false
